### ISSUE TITLE
[FEAT] 유저 개인프로필(히스토리) GUI 적용

### ISSUE THREAD

**Issue by dayo2n** [Nexters/momo-iOS#86]
## TODO
- [x] ProfileView는 #80 이 머지되면 그대로 사용
- [x] 출결 현황 Collection View GUI
- [x] 출석 히스토리 Table View GUI
- [x] tableview, collectionview 스크롤막고 화면 전체 스크롤

<img width="326" alt="스크린샷 2023-02-26 오전 5 52 25" src="https://user-images.githubusercontent.com/57654681/221379124-1e405fac-359c-4a3e-b468-04d3440ab55a.png">
